### ISSUE TITLE
Structure config to allow multiple Omeka instances

### ISSUE THREAD

**Issue by bibliotechy** [kelynch/picha#4]
Should be able to specify multiple URL + API Keys in the config file so that multiple sites can be shimmed.  Something like:

``` yaml

omeka1:
  API_key: KEY1
  URL: http://url.example1.com
```
